#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Matt Wittmann <mcwitt@gmail.com>

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# maybe source machine-specific zshrc
if [[ -s ".local/zshrc" ]]; then
  source "$HOME/.local/zshrc"
fi

# make vim mode more palatable by halving the key delay,
# which is in tenths of a second
export KEYTIMEOUT=2

# source shared source from stroxler/config repo
source "$HOME/shared-source.sh"

# make reloading environment easier
alias sxrc='source ~/.zshrc'

# source fzf bindings for zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
